org: pyxis
service: tpl-server

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  tracing:
    apiGateway: true
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
